# Numpy

## 파이썬 리스트와 넘파이 배열 속도 비교

In [13]:
python_list = [i for i in range(10**6)]

In [14]:
import numpy as np

arr = np.array(python_list)

In [15]:
%%timeit
sum(python_list)

7.39 ms ± 65.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
%%timeit
np.sum(arr)

381 µs ± 62.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## 넘파이 배열 생성과 기본 속성

In [17]:
arr1 = np.array([1,2,3])

type(arr1)

numpy.ndarray

In [18]:
print(arr1)
print([1, 2, 3]) # 파이썬 리스트
arr1

[1 2 3]
[1, 2, 3]


array([1, 2, 3])

In [19]:
arr1.shape

(3,)

In [20]:
a = [2,2]
type(a)

list

In [21]:
b= ()
type(b)

tuple

In [22]:
c = (2)
type(c)

int

In [23]:
d = (2 , )
type(d)

tuple

In [24]:
# 리스트는 데이터 교체 가능
l = [1, 2, 3]
l[0] = 3
print(l)

# 튜플은 데이터 교체 불가능
t = (1,2,3)
# t[0] = 3 # 오류 발생
print(t)

# 리스트와 튜플은 데이터 교체하지 않으면 대부분이 비슷함

[3, 2, 3]
(1, 2, 3)


In [25]:
arr2 = np.array([[1,2],[3,4],[5,6]])
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
arr3 = np.array([[[1,2],[3,4]],
                 [[6,5],[7,8]],
                 [[4,6],[5,5]]])

arr3.shape

(3, 2, 2)

In [27]:
arr3.dtype

dtype('int64')

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.linspace(0,10,5) # 10까지 5등분

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
np.arange(10) # 0~9까지

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 인덱싱(indexing)과 슬라이싱(slicing)

In [32]:
arr = np.array([0, 1, 2, 3, 4])
arr[-2]

3

In [33]:
arr = np.array([[1,2],[3,4],[5,6]])
arr[0][0]

1

In [34]:
arr[0,0]

1

In [35]:
arr[0, ]

array([1, 2])

- 불리언 인덱싱(Boolean indexing)

In [36]:
arr = np.array([0, 1, 2, 3, 4])
arr[1:3] # 1~2번째 인덱스

array([1, 2])

In [37]:
arr = np.array([0, 1, 2, 3, 4])
b = [False, True, False, True, True]
arr[b]

array([1, 3, 4])

In [38]:
arr>3

array([False, False, False, False,  True])

In [39]:
arr[arr>3]

array([4])

In [40]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr2[arr2>2]

array([3, 4, 5, 6])

In [41]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
print(arr[3:]) # 3~9
print(arr[3:-1]) # 3~8
print(arr[:])
print(arr[-4:])

[3 4 5 6 7 8 9]
[3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]


## 배열의 연산

In [43]:
a = [1,2,3]
b = [3,4,5]

print(a+b) # 리스트의 덧셈

[1, 2, 3, 3, 4, 5]


In [44]:
a = np.array([1,2,3])
b = np.array([3,4,5])

print(a+b) # 넘파이의 덧셈

# 브로드캐스팅
print(a+1)
print(a+[1,1,1])

[4 6 8]
[2 3 4]
[2 3 4]


In [45]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [46]:
print(arr.sum())
print(np.sum(arr))
print(arr.mean())
print(np.mean(arr))

10
10
2.5
2.5


In [47]:
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr2.sum())
print(arr2.sum(axis=1))
print(arr2.mean(axis=0))

21
[ 6 15]
[2.5 3.5 4.5]


In [48]:
arr2.shape

(2, 3)

In [49]:
arr2.reshape(3,2) # (2,3) -> (3,2)로 변경

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
arr2.reshape(3,2,1) # 축 하나 증가

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [51]:
arr2 = [[1],[2],[3]]
arr2

[[1], [2], [3]]